### PR TITLE
Use Forge's `clientSideOnly` feature

### PR DESCRIPTION
**Pull request by PaintNinja**
`clientSideOnly` skips loading your mod on dedicated servers and sets an appropriate DisplayTest for you. This simplifies some code by removing the need for classloading workarounds and the lengthy DisplayTest extension point registration code.

### CODE REVIEW

**Comment by tr7zw** [comment]
``clientSideOnly=true`` is not a valid flag and does nothing.

**Comment by PaintNinja** [comment]
It's valid on Forge 1.20.4, I made the feature myself... https://github.com/MinecraftForge/MinecraftForge/commit/8445f73b2d7046b85095110ce029937c10062c18

**Comment by tr7zw** [comment]
That would have been great, many, many years ago. EntityCulling is not yet transformed, but the code base(will) have to work for 1.16-1.20 and on Forge/NeoForge/Fabric. So I much rather have that logic equal between all of them, than a special case for 1.20.4 Forge alone.

**Comment by PaintNinja** [comment]
This is more removing the need for a special case for Forge than adding one, as it no longer needs the bootstrap workaround and extra code to prevent crashing servers, which in turn makes it closer to the Fabric version in that respect.

As for a single unified codebase for 1.16.5-1.20.4, this isn't possible with Neo as it doesn't exist on versions older than 1.20.1, so you'll be stuck with some special casing regardless. I may be misunderstanding your point here 🤔

If this feature was backported to older Forge versions, dating back to 1.16.5, would you be more open to accepting this PR?

**Comment by tr7zw** [comment]
I guess also of note: I did bring this up back in October of last year on the NeoForge discord, and as told that a clientSideOnly flag will not be added ( https://discord.com/channels/313125603924639766/313125603924639766/1168852309070073899 ). So a bit weird to see this was added 2 months later to Forge.

**Comment by tr7zw** [comment]
> If this feature was backported to older Forge versions, dating back to 1.16.5, would you be more open to accepting this PR?

Makes it tricky with servers using old Forge version(and 1.16/1.17/1.18 afaik not getting updates). 
> so you'll be stuck with some special casing regardless.

Over on an already ported mod it looks like this: https://github.com/tr7zw/3d-Skin-Layers/blob/main/src/main/java/dev/tr7zw/skinlayers/SkinLayersBootstrap.java https://github.com/tr7zw/3d-Skin-Layers/blob/main/src/main/java/dev/tr7zw/skinlayers/SkinLayersModBase.java#L15
So 2 lines in the mod file and the bootstrap class with is just a copy paste between the mods. And that does the trick for NeoForge/Forge and 1.16-1.20 just fine so far.

**Comment by tr7zw** [comment]
If NeoForge 1.20.4 also supports this flag, disabling the bootstrap and the display test for 1.20.4+ Forge/NeoForge in my template might be a good idea. (at least one less file and method to maintain in the future)

**Pull request closed without merging**
