### PR TITLE
Add Draconic Evolution's TileEntities to default config for 1.16

### PR DESCRIPTION
**Pull request by gardenappl**
Might want to repeat this change on 1.17 as well, but I picked the 1.16-backport branch because DE is only on 1.16 for now.

### CODE REVIEW

**Comment by gardenappl** [comment]
I wonder if this will become unnecessary once https://github.com/tr7zw/EntityCulling/issues/51 is fixed.

**Comment by tr7zw** [comment]
I'll look into it once I'm back to modding because I'm done with uni projects (1-2 weeks).

**Comment by tr7zw** [comment]
With the forge #51 change, this seems to work without? Please give it a test.

**Comment by gardenappl** [comment]
Yeah, latest version works fine without the blacklist, thanks!

**Comment by tr7zw** [comment]
Perfect 👍

**Pull request closed without merging**
