### PR TITLE
gradle: Fix executable bit

### PR DESCRIPTION
**Pull request by 5HT2**
This fixes the gradle compose script not being marked as executable for Linux and macOS systems.

### CODE REVIEW

**Comment by tr7zw** [comment]
This problem probably stretches over all my repos. I work on windows, and the CI file starts with a `chmod +x ./gradlecw`. But doesn't hurt to fix it I guess.

**Comment by tr7zw** [comment]
@5HT2 Also fyi, you copied the `This fixes the gradle compose script not being marked as executable for Linux and macOS systems.` into the other PR's from other repos. Gradle compose is my own custom tooling, in the other repos it's the normal gradle wrapper, not "compose".

**Comment by 5HT2** [comment]
> @5HT2 Also fyi, you copied the `This fixes the gradle compose script not being marked as executable for Linux and macOS systems.` into the other PR's from other repos. Gradle compose is my own custom tooling, in the other repos it's the normal gradle wrapper, not "compose".

Oh god that's embarrassing. Thank you for pointing it out, I realized earlier that gradle compose was something I had not seen before :p I should have changed the commit message back to just gradle.

I've just been porting mods for myself and fixing the chmod bits along the way when people forget to enable it, I didn't pay too much attention when making the commits :sob:

**Comment by tr7zw** [comment]
Happens :D. I just wrote that small "compose" wrapper around the gradle wrapper that spawns data managed at https://github.com/tr7zw/ModComposeTemplate/tree/1.19.4 using the https://github.com/tr7zw/EntityCulling/blob/1.19.4/gradle-compose.yml file. Otherwise I'd go insane managing all the Forge/Fabric dependencies/CI scripts/Gradle files/small utility classes/etc over 10? projects with 6+ version branches each. In the end I'm just one person doing this for fun^^.

**Comment by 5HT2** [comment]
that's very cool !! thank you for explaining what it is c:

**Pull request merged**
